### PR TITLE
Jupiter: Usability for Products without the Tenant Framework

### PR DESCRIPTION
**Pull request by jakobvogel**
Enables products that do not use the _Tenants_ framework to use Jupiter by providing the system tenant differently.

### CODE REVIEW

**Review by sabieber — APPROVED** [review]
Couldn't MEMOIO register its own `Tenants` class that just provide the ID an name?

**Comment by jakobvogel** [comment]
> Couldn't MEMOIO register its own `Tenants` class that just provide the ID an name?

The `Tenants` class is rather large, and implementing it may inadvertently enable other functionality. For now, I would like to keep a clear separation, and maintain the hope that one day, we will be able to migrate MEMOIO to use the tenants framework as well. 🤞

**Comment by sabieber** [comment]
> The `Tenants` class is rather large, and implementing it may inadvertently enable other functionality. For now, I would like to keep a clear separation, and maintain the hope that one day, we will be able to migrate MEMOIO to use the tenants framework as well. 🤞

Yeah but implementing workarounds in various places throughout the framework until that day comes doesn't sound desirable as well 😶

**Comment by jakobvogel** [comment]
> Yeah but implementing workarounds in various places throughout the framework until that day comes doesn't sound desirable as well 😶

Correct, neither are desirable solutions. But comparing effort, possible side effects, resources, etc., the proposed way of this PR still seems to be the more justifiable one to me — or we decide not to use _Jupiter_ for MEMOIO, which would lead to incomplete support of the knowledge base, and with it, of the API documentation.

**Comment by sabieber** [comment]
No I certainly don't want to hinder usage of Jupiter/DataVault in MIO :)
Also thought about other workaround options like overwriting the Sync but all I came up with wasn't easily implementable.

**Review by mkeckmkeck — APPROVED** [review]

**Comment by sabieber** [comment]
Sadly the `framework` setting in the `@Register` annotation only allows for a single framework to be mentioned, otherwise we could set jupiter + tenants there and MIO could inherit the class, overwrite the two methods and register it itself.

**Review by mko-sci — APPROVED** [review]

**Pull request merged**
